# Stage 1 : Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ../*.sln ./
COPY Client/*.csproj ./Client/
RUN dotnet restore

COPY Client/. ./Client/
WORKDIR /src/Client
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Stage 2 : Runtime Nginx
FROM nginx:alpine AS runtime
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
